# Hugo 설정 — 문서: https://docs.hugoblox.com/reference/
title: NeuroAI Lab
baseURL: 'https://neuroailab.com/'   # GitHub Actions 빌드 시 --baseURL 로 덮어씀

############################
## LANGUAGE
############################
defaultContentLanguage: ko
hasCJKLanguage: true
defaultContentLanguageInSubdir: true   # /ko/ , /en/
removePathAccents: true

############################
## ADVANCED
############################
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  jpeg:
    quality: 75
  webp:
    quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
